dynamodb:
  localInstance: false
  table: EventStoreCargo_Dev

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mariadb://localhost:3306/camunda_poc
    username: poc
    password: poc
    driver-class-name: org.mariadb.jdbc.Driver
