/*
 * Copyright (C) Schweizerische Bundesbahnen SBB, 2016.
 */

package ch.sbb.dks.camundapoc;


import org.springframework.boot.SpringApplication;

import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Spring boot config for the application.
 *
 * @author ue64007 (Manuel Wallrapp), generated by ESTA Initializr
 * @since 1.0.0, 2017.
 */
@SpringBootApplication
public class CamundaPocApp {

    public static void main(String[] args) {
        SpringApplication.run(CamundaPocApp.class, args);
    }
}
